services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./migrations:/app/migrations

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 3s
      timeout: 3s
      retries: 3



  postgres:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:

networks:
  app-network:
    name: app-network
