"""speaker-table

Revision ID: 931d6e42a48b
Revises: 93e90425d93e
Create Date: 2025-05-20 14:02:39.576793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931d6e42a48b'
down_revision: Union[str, None] = '93e90425d93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speakers',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_email'), 'speakers', ['email'], unique=True)
    op.create_index(op.f('ix_speakers_name'), 'speakers', ['name'], unique=False)
    op.add_column('talks', sa.Column('speaker_id', sa.String(length=26), nullable=False))
    op.create_foreign_key(None, 'talks', 'speakers', ['speaker_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('talks', 'speaker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talks', sa.Column('speaker', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'talks', type_='foreignkey')
    op.drop_column('talks', 'speaker_id')
    op.drop_index(op.f('ix_speakers_name'), table_name='speakers')
    op.drop_index(op.f('ix_speakers_email'), table_name='speakers')
    op.drop_table('speakers')
    # ### end Alembic commands ###
