name: Run Tech Floripa Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright rich beautifulsoup4

    - name: Install Playwright browsers
      run: |
        playwright install --with-deps chromium

    - name: Run scraper
      run: |
        python scrapper.py
