name: Run Tech Floripa Scraper

on:
  schedule:
    - cron: '0 9,21 * * *'  # 06:00 e 18:00 horário de Brasília]

  workflow_dispatch:

jobs:
  scrape-tech-floripa:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Generate requirements.txt
        run: |
          echo "playwright" > requirements.txt
          echo "rich" >> requirements.txt
          echo "beautifulsoup4" >> requirements.txt

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browser
        run: |
          playwright install chromium

      - name: Run scraper
        run: |
          python scrapper.py

      - name: Clean up requirements.txt
        run: rm requirements.txt

      - name: Commit and push JSON output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add events.json
          git commit -m "Atualiza Tech Floripa events"
          git push
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
